import type { DevelopmentFeatureInput } from "../../domain/development-feature";

export const DEVELOPMENT_DEMO_SEED_VERSION = 1;

export const DEVELOPMENT_DEMO_FEATURES: ReadonlyArray<
  DevelopmentFeatureInput & { id: string }
> = [
  {
    component: "Gmail",
    dependencies: [],
    description: "Attach Gmail conversations to Plays with a simple physical drag workflow.",
    id: "2eb76847-7998-4a10-8f58-629d3447f1d4",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "High",
    sequence: 1,
    status: "Done",
    title: "Drag Email into PlayHouse",
  },
  {
    component: "Calendar",
    dependencies: [],
    description: "Show relevant calendar events alongside dated Plays.",
    id: "205d0598-b93c-49e1-aec3-4dac945e6e0a",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "High",
    sequence: 2,
    status: "Planned",
    title: "Calendar Events in Plays",
  },
  {
    component: "Roller",
    dependencies: [],
    description: "Summarize the day's Roller decisions and explain important schedule changes.",
    id: "59b66238-f021-4bbb-94ee-d7b7fed800a6",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "Medium",
    sequence: 3,
    status: "Idea",
    title: "Roller Daily Summary",
  },
  {
    component: "PlayHouse",
    dependencies: [],
    description: "Create reusable starting points for recurring kinds of Plays.",
    id: "58e924f8-6655-49a0-acba-e1855d3135ba",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "Medium",
    sequence: 4,
    status: "Ready",
    title: "Play Templates",
  },
  {
    component: "Slack",
    dependencies: [],
    description: "Connect Slack conversations and people to Carnival context.",
    id: "cf9c7d41-1004-4ef3-b320-250105bd818a",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "Medium",
    sequence: 5,
    status: "Building",
    title: "Slack Integration",
  },
  {
    component: "Mobile / PWA",
    dependencies: [],
    description: "Deliver the first focused mobile PlayHouse experience.",
    id: "6416e0db-d259-4932-ad1e-3a132261a191",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "High",
    sequence: 6,
    status: "Planned",
    title: "Mobile App (MVP)",
  },
  {
    component: "Chrome Extension",
    dependencies: [],
    description: "Simplify and harden the browser bridge for Carnival's desktop workspace.",
    id: "af41eaef-225e-4d29-a384-da0931841dc7",
    notes: "Demo roadmap entry — replace with approved requirements.",
    priority: "Low",
    sequence: 7,
    status: "Testing",
    title: "Chrome Extension v2",
  },
  {
    component: "Carnival AI",
    dependencies: [],
    description: "Explore assistance grounded in Carnival Plays, sequence, and relationships.",
    id: "9dcd617f-011e-40d7-a49c-f0c72603d551",
    notes: "Demo roadmap entry — not an approved AI implementation requirement.",
    priority: "Low",
    sequence: null,
    status: "Idea",
    title: "AI Play Assistant",
  },
];
